const f = require('fs');
const pages = {
  'hidden-fee-glossary.html': { h2: 'Hidden Fee Glossary: Terms Consumers Should Know', body: '<p>This glossary defines important hidden fee terms that every consumer should understand. Being familiar with these terms helps you identify charges on bills and contracts.</p><h3>Common Fee Types</h3><p>Overdraft fees occur when banks cover transactions exceeding your balance. Monthly maintenance fees are charges for keeping a bank account open. Foreign transaction fees apply to purchases made in other currencies. Late payment fees are penalties for missing payment due dates. Administrative fees cover unspecified overhead costs that companies add to bills. Documentation fees are charges for processing paperwork that often far exceed actual costs. Equipment rental fees are recurring charges for leasing devices you could buy outright. Regulatory recovery fees are company-imposed charges disguised as government requirements.</p><h3>Contract Terms</h3><p>Escalation clauses allow automatic price increases each year. Auto-renewal clauses extend contracts without notice. Termination fees penalize you for ending agreements early. Indemnification requires you to cover the other party legal costs. Arbitration requires disputes to be resolved outside of court. Assignment allows companies to transfer your contract to another party.</p>'},
  'hidden-fee-reports.html': { h2: 'Hidden Fee Reports: Industry Research and Data', body: '<p>Our reports analyze hidden fee practices across industries, providing data-driven insights for consumers. Each report examines specific fee types and offers recommendations for avoiding them.</p><h3>Banking Fee Report 2026</h3><p>Banks generated over $32 billion in fee revenue last year. Overdraft fees account for $11 billion. Monthly maintenance fees generate $8 billion. Transaction reordering practices maximize fee collection.</p><h3>Healthcare Billing Report</h3><p>Medical billing errors total $68 billion annually. Duplicate charges affect 30% of patients. CPT code upcoding is found in 22% of bills. Facility fees add $50-$200 per visit.</p><h3>Automotive Fee Report</h3><p>Dealerships generate $26 billion through hidden fees. Documentation fees average $699 in unregulated states. Dealer add-on markups range from 100% to 500%.</p>'},
  'medical-bill-negotiation-template.html': { h2: 'Medical Bill Negotiation: Step-by-Step Guide', body: '<p>Medical bills are the most common source of hidden overcharges. This guide walks you through the process of reviewing and disputing medical bills effectively.</p><h3>Step 1: Request an Itemized Bill</h3><p>Hospitals are required to provide itemized bills upon request. Compare each charge against your insurance Explanation of Benefits. Look for duplicate procedure codes, incorrect dates of service, and charges for services not received.</p><h3>Step 2: Verify CPT Codes</h3><p>CPT codes determine what you are charged. Verify each code matches the service received. Upcoding is a common practice where providers bill for more expensive procedures than performed. Request code corrections from your provider.</p><h3>Step 3: Check for Duplicate Charges</h3><p>Duplicate billing occurs when the same procedure appears multiple times on your bill. This can happen with lab tests, imaging studies, and surgical supplies. Flag each duplicate and request removal.</p>'},
  'negotiation-scripts.html': { h2: 'Negotiation Scripts: What to Say When Asking for Fee Removal', body: '<p>Having the right words makes fee negotiation significantly more successful. These scripts give you proven language that works across different types of fees and providers.</p><h3>Late Fee Waiver Script</h3><p>Call the customer service number and say: I am reviewing my recent statement and noticed a late fee of $[amount]. I have been a customer for [X] years and have a good payment history. I am hoping you can waive this as a one-time courtesy. This approach works 60-70% of the time for first requests.</p><h3>Rate Reduction Script</h3><p>Call and ask for the retention department directly. Say: I have been reviewing my options and competitor [Name] is offering the same service for $[amount] less per month. I want to stay with your company but I need a better rate to justify staying. Can you match or beat this offer?</p>'},
  'service-agreement-red-flags.html': { h2: 'Service Agreement Red Flags: Warning Signs to Watch For', body: '<p>Service agreements contain terms that can cost you money for years. Knowing the red flags helps you negotiate better terms before signing.</p><h3>Vague Pricing Language</h3><p>Watch for phrases like standard rates, market rates, or reasonable fees. These undefined terms give providers the right to charge whatever they want. Require specific dollar amounts for every fee mentioned in the agreement.</p><h3>Automatic Renewal Clauses</h3><p>Many service agreements renew automatically with higher rates. Look for renewal terms carefully and require written notice before any renewal. Set calendar reminders 60 days before renewal dates.</p><h3>Unlimited Liability Disclaimers</h3><p>Some agreements limit provider liability while leaving you fully responsible for damages. Fair contracts have mutual limitations. Require liability caps that apply equally to both parties.</p>'}
};

Object.entries(pages).forEach(([file, data]) => {
  if(!f.existsSync(file)) return;
  let c = f.readFileSync(file, 'utf8');
  c = c.replace(/<h2>How to Negotiate Bills Successfully<\/h2>[\s\S]*?<section/, `<h2>${data.h2}</h2>${data.body}<section`);
  f.writeFileSync(file, c);
  console.log('Fixed:', file);
});

// Verify
let rem = 0;
f.readdirSync('.').filter(x => x.endsWith('.html')).forEach(x => {
  try { const c = f.readFileSync(x, 'utf8').toLowerCase(); if (c.includes('how to negotiate bills successfully')) rem++; } catch(e) {}
});
console.log('Remaining:', rem);
if (rem === 0) console.log('✅ ALL PHRASE DUPLICATES ELIMINATED');