const fs = require('fs');
const path = require('path');
const dir = 'c:\\Users\\lynns\\Downloads\\detecthiddenfees.com';

function expandFile(name, html) {
  const fp = path.join(dir, name + '.html');
  if (!fs.existsSync(fp)) { console.log('MISSING: ' + name); return; }
  let c = fs.readFileSync(fp, 'utf8');
  const start = c.indexOf('class="container long-content"');
  if (start === -1) { console.log('NO CONTENT: ' + name); return; }
  const h2 = c.indexOf('<h2>', start);
  const se = c.indexOf('</section>', h2);
  if (h2 === -1 || se === -1) { console.log('NO END: ' + name); return; }
  c = c.substring(0, h2) + '\n' + html + '\n' + c.substring(se);
  fs.writeFileSync(fp, c, 'utf8');
  console.log('EXPANDED: ' + name);
}

expandFile('hidden-credit-card-fees', '<h2>Hidden Credit Card Fees: What Card Companies Do Not Advertise</h2><p>Credit cards come with a complex fee structure that most consumers never fully understand, costing them hundreds of dollars per year in unnecessary charges. Foreign transaction fees of 1% to 3% apply to every purchase made outside the United States, including online purchases from foreign merchants. This means a $1,000 international purchase could cost you an extra $30 simply because of a fee that is buried in the fine print of your cardholder agreement. Many cards marketed as travel cards specifically advertise no foreign transaction fees, but cards without this feature charge them on every international transaction. Balance transfer fees typically range from 3% to 5% of the amount transferred. While promotional balance transfer offers often advertise low or zero interest rates for an introductory period, the upfront fee can make the transfer significantly more expensive than it appears at first glance. On a $10,000 balance transfer, a 5% fee adds $500 to your debt immediately before you save a single dollar in interest. Cash advance fees of 3% to 5% are charged when you use your credit card to obtain cash, and unlike regular purchases, interest on cash advances begins accruing immediately with no grace period. The APR for cash advances is also typically higher than the purchase APR. Annual fees, late payment penalties that can reach $41 per occurrence, returned payment fees, over-limit fees, and expedited card delivery fees can all add additional charges to your account throughout the year. The Credit CARD Act of 2009 requires card issuers to provide clear disclosures about fees, but many consumers still do not read the fine print carefully before applying for a new card.</p>');

expandFile('hidden-loan-fees', '<h2>Hidden Loan Fees: The True Cost of Borrowing Revealed</h2><p>Loans appear straightforward at first glance: you borrow a specific amount and pay it back with interest over a set period. But the fine print of most loan agreements contains fees that can significantly increase the total cost of borrowing beyond what the interest rate alone suggests. Origination fees are one of the most common and expensive hidden loan costs. Lenders charge these fees for processing the loan application, verifying your information, and funding the loan. Origination fees typically range from 0.5% to 6% of the total loan amount and are deducted from the loan proceeds before you receive the funds. On a $20,000 personal loan with a 5% origination fee, you would pay $1,000 in fees before you even receive the money, meaning you are paying interest on the full $20,000 but only receiving $19,000 to use. Prepayment penalties are another fee to watch for carefully. Some lenders charge a fee if you pay off your loan early, which is counterintuitive because paying off debt early should be encouraged. These penalties are typically calculated as a percentage of the remaining balance and can be substantial, especially in the first few years of the loan. Late payment fees of $25 to $50 per occurrence, application fees that are non-refundable even if your loan is denied, processing fees for document preparation, and annual maintenance fees on certain types of credit lines can all add to your total borrowing costs. When comparing loan offers, always look at the Annual Percentage Rate rather than just the interest rate because the APR includes many of these fees in its calculation and provides a more accurate comparison of the total cost of borrowing from different lenders.</p>');

expandFile('hidden-mortgage-fees', '<h2>Hidden Mortgage Fees: What Your Lender Might Not Explain</h2><p>Buying a home involves a mountain of fees, and many of them are inflated or unnecessary. Understanding the typical closing costs and their reasonable ranges helps you identify when you are being overcharged and negotiate better terms with your lender. Origination points are one of the most significant mortgage fees. Each point equals 1% of the loan amount and is paid upfront in exchange for a lower interest rate. While points can be a good value if you plan to stay in the home long enough to recoup the upfront cost through lower monthly payments, some lenders add points to your loan without clearly explaining the trade-off between the upfront cost and the long-term savings. Third-party service fees are another area where significant markups occur. Lenders often charge more than the actual cost for services like appraisals, title searches, credit reports, and flood certifications. The difference between what the lender charges you and what the third party actually charges the lender is pure profit. Application fees, processing fees, underwriting fees, and document preparation fees can add thousands of dollars to your closing costs. Many of these fees cover the same underlying work and represent overlapping charges that can be reduced or eliminated with negotiation. Request a Loan Estimate from every lender you are considering and compare the total closing costs line by line. Ask each lender to explain any fees that are higher than what other lenders are charging for the same service. Many closing costs are negotiable, and lenders who want your business will often match lower offers from competing lenders.</p>');

expandFile('hidden-investment-fees', '<h2>Hidden Investment Fees: How Fund Expenses Reduce Your Returns</h2><p>Investment fees silently erode your returns year after year, often without you realizing how much they are costing you because they are deducted automatically from your account rather than billed separately. Management expense ratios are the most significant ongoing cost for mutual funds and exchange-traded funds. A difference of even 0.5% in annual fees can amount to tens of thousands of dollars over a lifetime of investing due to the power of compound returns. A fund with a 0.03% expense ratio costs you $3 per year for every $10,000 invested, while a fund with a 1.5% expense ratio costs you $150 per year for the same amount. Over 30 years, that difference compounds to hundreds of thousands of dollars in lost returns. Load fees are another expensive hidden cost in investing. Front-end loads are charged when you buy certain mutual funds and can be as high as 5.75% of your investment amount. On a $10,000 investment, a 5.75% front-end load means you lose $575 immediately before your money even begins working for you. Back-end loads are charged when you sell certain funds and typically decrease over time. Account maintenance fees, annual account fees, transaction fees for buying and selling, advisory fees charged by financial advisors, and 12b-1 marketing fees that cover the cost of promoting the fund to investors can all add additional layers of cost that reduce your investment returns. The Securities and Exchange Commission requires funds to disclose their fees in a standardized fee table, but many investors never read this disclosure. Review the fee table for every investment you own and consider switching to lower-cost alternatives that can save you significant money over time without sacrificing performance.</p>');

expandFile('hidden-internet-fees', '<h2>Hidden Internet Fees: What Your ISP Is Not Telling You</h2><p>Internet service providers are notorious for adding fees to monthly bills that can increase your actual cost by 30% or more above the advertised price. Equipment rental fees of $10 to $15 per month for a modem and wireless router that you could purchase outright for under $100 can cost you hundreds of dollars over the lifetime of your service. A modem that costs $80 to buy will cost you $120 to $180 in rental fees in the first year alone, and you will continue paying for it every year you remain a customer. Installation and activation fees of $50 to $200 are charged even when the equipment is designed for easy self-installation. Some providers will waive these fees if you ask, but they do not offer proactively. Early termination penalties of up to $400 make it financially painful to switch providers even when you are unhappy with the service or find a better deal elsewhere. Data overage fees that trigger when you exceed your monthly data cap, price increases that take effect after promotional introductory periods expire, and regulatory recovery fees that are presented as pass-through charges from government requirements but are actually set by the provider at whatever level they choose are all additional fees that can inflate your monthly bill. When comparing internet service offers, ask each provider for a complete breakdown of the total monthly cost including all fees and taxes, not just the promotional base price. Compare the total cost rather than the advertised price to get an accurate picture of what you will actually pay each month.</p>');

expandFile('hidden-phone-bill-fees', '<h2>Hidden Phone Bill Fees: Understanding Your Carrier Charges</h2><p>Phone bills are filled with fees that carriers add with minimal explanation, making it difficult to understand what you are actually paying for each month. Regulatory and administrative fees are among the most confusing charges on phone bills. Carriers add these fees to cover the cost of complying with government regulations, but the amounts are not regulated by any government agency and vary widely between carriers. One carrier might charge $1.50 while another charges $3.50 for the exact same set of regulatory requirements. Activation and upgrade fees of $25 to $50 are charged when you start new service or upgrade your phone to a newer model. These fees can often be waived if you ask, but the carrier will not offer to waive them proactively. Premium SMS subscriptions for ringtones, wallpapers, and other services can be added to your account without your clear authorization, resulting in charges of $10 to $30 per month for services you never intentionally ordered. Directory assistance charges of $2 to $5 per call, international calling fees that apply even when you do not make international calls, and data overage charges that can reach $15 per gigabyte are other common sources of hidden charges. Third-party charges from companies you have never heard of can also appear on your phone bill through a practice called cramming, where small charges are added for services you never authorized. Review every line item on your phone bill each month and dispute any charges that you do not recognize or understand. Federal regulations require carriers to investigate and remove unauthorized charges when you dispute them.</p>');

expandFile('hidden-subscription-fees', '<h2>Hidden Subscription Fees: Stop Paying for Services You Forgot</h2><p>Subscriptions are designed to be forgotten. Companies that offer subscription services count on a certain percentage of customers continuing to pay month after month for services they no longer use or even remember signing up for. Auto-renewal clauses are the primary mechanism that makes this possible. Most subscription agreements include terms that automatically renew your subscription at the end of each billing period unless you take specific action to cancel before the renewal date. Some companies make cancellation intentionally difficult by requiring phone calls during limited business hours, not providing confirmation of cancellation, or requiring multiple steps to complete the process. Free trial conversions are one of the most common subscription traps. You sign up for a free trial of a service, intending to cancel before the trial period ends, but you forget to cancel and your credit card is charged the full subscription price. Some companies make it particularly difficult to cancel during the trial period, requiring you to call and speak with a retention specialist who will try to convince you to stay. Price increases on existing subscriptions are another hidden cost. Many subscription services reserve the right to increase prices at any time with minimal notice to existing customers. You may be paying a higher price for months or years without realizing the rate has increased because the charge is automatically deducted from your account each month. Add-on subscriptions that are bundled with main services, forgotten subscriptions from years ago that continue charging your credit card, and subscriptions that continue after you have stopped using the service all contribute to the growing problem of subscription creep. Review your bank and credit card statements every month specifically looking for recurring charges you no longer need or want. Cancel any subscriptions you are not actively using and consider using a subscription management service to track all of your recurring expenses in one place.</p>');

expandFile('hidden-streaming-fees', '<h2>Hidden Streaming Fees: Price Hikes and Unexpected Charges</h2><p>Streaming services have become a major household expense, and companies in this space are continuously finding new ways to increase the amount you pay each month. Ad-free tier upcharges are becoming a common hidden cost as streaming services introduce lower-priced ad-supported plans. If you signed up for a premium plan that was originally ad-free, you may now be paying a premium price for a service that has quietly added commercials through tier restructuring. Some services have moved content that was previously included in the base subscription to higher-priced tiers, effectively raising your cost if you want to maintain access to the same content library. Account sharing restrictions are another emerging cost that is catching many subscribers by surprise. Several major streaming services have begun actively enforcing rules against password sharing and charging extra fees for accounts that are accessed from multiple households. These fees can add $5 to $10 per month per additional household, significantly increasing your total streaming costs if you share accounts with family members. 4K Ultra HD streaming surcharges of $5 to $10 per month above the base subscription price, simultaneous stream limits that require upgrading to a more expensive plan to watch on multiple devices at the same time, and annual price increases that are quietly applied to existing subscribers all contribute to the rising cost of streaming entertainment. The best way to manage streaming costs is to review your subscriptions quarterly, rotate services based on what you are actually watching, and cancel any services you have not used in the past 30 days. Most streaming services make it easy to cancel and resubscribe, so there is no penalty for being selective about which services you maintain at any given time.</p>');

console.log('Batch 2 done - financial, internet, phone, subscription, streaming fees');
