const fs = require('fs');
const path = require('path');
const dir = 'c:\\Users\\lynns\\Downloads\\detecthiddenfees.com';

function expandFile(name, html) {
  const fp = path.join(dir, name + '.html');
  if (!fs.existsSync(fp)) { console.log('MISSING: ' + name); return false; }
  let c = fs.readFileSync(fp, 'utf8');
  const start = c.indexOf('class="container long-content"');
  if (start === -1) { console.log('NO CONTENT: ' + name); return false; }
  const h2 = c.indexOf('<h2>', start);
  const se = c.indexOf('</section>', h2);
  if (h2 === -1 || se === -1) { console.log('NO END: ' + name); return false; }
  c = c.substring(0, h2) + '\n' + html + '\n' + c.substring(se);
  fs.writeFileSync(fp, c, 'utf8');
  console.log('EXPANDED: ' + name);
  return true;
}

expandFile('hidden-plumbing-fees', '<h2>Hidden Plumbing Fees: Complete Guide to Avoiding Overcharges</h2><p>Plumbing contractors have pricing tactics that can turn a simple repair into an expensive bill. The most common hidden fee is the diagnostic or trip charge that plumbers add simply to come to your home. This fee typically ranges from $50 to $200 and is sometimes applied separately from the repair cost without clear disclosure. Always ask whether the diagnostic fee is waived if you proceed with the repair work. Material markups are another significant area where costs escalate. Contractors typically mark up parts by 20% to 50% above their wholesale cost, but some charge 100% or more for fittings, valves, and fixtures. Ask for an itemized parts list showing cost and markup before approving work. Emergency service premiums can double or triple standard rates for after-hours or weekend calls. Before authorizing emergency service, get the complete pricing including hourly rate, dispatch fees, and estimated time. Additional charges that frequently appear on plumbing invoices include permit fees charged above actual cost, disposal fees for old fixtures, and administrative fees for paperwork. Some plumbers also charge for estimates on larger projects. Always get a written estimate with all potential charges before authorizing any plumbing work, and question any fees that are not clearly explained.</p>');

expandFile('hidden-electrician-fees', '<h2>Hidden Electrician Fees: What Electrical Contractors Don\'t Disclose</h2><p>Electrical work requires genuine expertise, but that does not mean you should pay inflated prices due to hidden fees. Service call fees of $50 to $150 for showing up are common, so ask whether this fee is credited toward the repair if you proceed with the work. Emergency service premiums can double or triple regular rates for after-hours or weekend electrical service. While some premium is reasonable, the markup should be clearly disclosed before you agree to emergency work. Material markups on parts like breakers, wiring, fixtures, and specialty components can add substantial costs to your project. Some electricians charge 100% or more above wholesale for common parts. Permit and inspection fees are sometimes charged at rates significantly above the actual cost charged by the local building department. Always get an itemized quote before authorizing any electrical work and ask about any fees that are not clearly explained in the estimate. Understanding these potential charges before you agree to service helps you evaluate quotes fairly and avoid disputes when the final bill arrives. A reputable electrician should be willing to provide a detailed written estimate with all charges clearly itemized before work begins.</p>');

expandFile('hidden-roofing-contractor-fees', '<h2>Hidden Roofing Contractor Fees: Protect Your Home Investment</h2><p>Roofing projects are among the most expensive home improvements, and contractors have many opportunities to add hidden fees that significantly increase your final cost beyond the initial quote. Tear-off and disposal fees are one of the most common hidden costs in roofing contracts. Some contractors include these in their base price while others add them as separate line items that can add thousands to your total. Always confirm whether tear-off and disposal are included in the quoted price or charged separately before signing any contract. Material cost fluctuation clauses are another area where roofing contractors can add hidden charges. Some contracts allow the contractor to pass on any material price increases to you without adjusting the initial quote, which can add thousands to your final bill if prices rise during the project. Permit and inspection fees, dumpster rental charges, and equipment rental fees are other areas where costs can escalate beyond the quoted amount. Always request a complete line-item breakdown of every charge in writing before signing a contract. Get at least three quotes from different contractors and compare them carefully to see where pricing differences exist. A significantly lower quote may indicate that the contractor has excluded important items that will be added later as change orders.</p>');

expandFile('hidden-moving-company-fees', '<h2>Hidden Moving Company Fees: Avoiding Surprise Charges on Moving Day</h2><p>Moving companies have a reputation for surprise charges that is unfortunately well-earned by years of consumer complaints. The most notorious hidden moving fee is the weight re-weigh scam, where movers quote a low estimate based on estimated weight then weigh the truck at the destination and claim the load is heavier than expected, demanding thousands of dollars more before they will unload your belongings. Protect yourself by getting a binding not-to-exceed quote that locks in the maximum price regardless of actual weight. Stair fees, long-carry fees for distances over a certain number of feet from the truck to your door, fuel surcharges, packing material markups, elevator fees for high-rise buildings, and shuttle fees when the moving truck cannot park close enough are all common additional charges that can add hundreds or even thousands of dollars to your move. Ask every moving company you receive a quote from for a complete written list of all potential additional charges that could apply to your specific move. Compare these lists between companies because the company with the lowest base rate may have the highest add-on fees. Get everything in writing, including the maximum price you will be charged, before allowing movers to load a single item.</p>');

expandFile('hidden-landscaping-fees', '<h2>Hidden Landscaping Fees: What Lawn Care Companies Don\'t Tell You</h2><p>Landscaping contracts often contain hidden fees that can inflate your monthly or annual bill significantly beyond what you expected based on the initial proposal. Fuel surcharges are becoming increasingly common in landscaping contracts, with some companies adding charges that are not tied to actual fuel consumption. Ask whether fuel surcharges are included in the base price or added separately, and request a cap on any variable surcharges that could increase without notice. Seasonal add-ons for services like leaf removal in the fall, snow removal in the winter, and spring cleanup in the spring can add costs for services you may have assumed were included in your regular service. Contract auto-renewal clauses with automatic price escalation, cancellation fees that apply even with proper notice, and trip charges for properties outside the standard service area are other hidden costs to watch for. Read your landscaping contract carefully before signing and make sure you understand exactly what services are included, what services cost extra, and how pricing can change over time. Ask for a full-year pricing breakdown that shows the cost for every month including any seasonal services or surcharges that apply throughout the year.</p>');

console.log('Industry fee pages expanded');
