const fs = require('fs');
const path = require('path');
const dir = 'c:\\Users\\lynns\\Downloads\\detecthiddenfees.com';

const pages = {};

pages['hidden-fees-resource-center'] = '<h2>Hidden Fees Resource Center: Your Starting Point for Fee Intelligence</h2><p>Welcome to the most comprehensive hidden fees resource center on the web. Our team has cataloged hundreds of hidden fees across every major industry, analyzed thousands of contracts and bills, and developed proven strategies to help you spot, challenge, and eliminate hidden charges. Whether you are dealing with a surprise medical bill, a contract full of fine-print surcharges, or a monthly statement with unexplained fees, this resource center connects you to the specific information and tools you need.</p><p>Hidden fees are not accidents. They are engineered into pricing structures, buried in legal language, and designed to go unnoticed. Companies spend millions of dollars optimizing their billing systems to maximize revenue from customers who do not push back. Our mission at DetectHiddenFees is to level the playing field by giving consumers the same intelligence that corporations use. This resource center organizes everything we have learned into an accessible, actionable format.</p><p>Start by exploring the industry guides below to understand the specific fees that apply to your situation. Then use our AI analysis tools to upload your documents and get a personalized report. Finally, visit our negotiation resources to prepare for your conversation with the billing department. Every section is designed to work together, guiding you from discovery to resolution.</p>';

pages['consumer-negotiation-resource-center'] = '<h2>Consumer Negotiation Resource Center: Master the Art of Paying Less</h2><p>Negotiation is the single most powerful financial skill most people never learn. This resource center teaches you how to negotiate everything from medical bills to service contracts, using proven strategies backed by AI-powered analysis. Whether you are preparing for a phone call with a hospital billing department or drafting an email to your internet provider, you will find the specific scripts, templates, and strategies you need to succeed.</p><p>Most people assume prices are fixed. They are not. Hospitals, service providers, contractors, and even subscription companies have flexibility built into their pricing systems. The question is not whether they can give you a better price. The question is whether you know how to ask for it, what evidence to present, and what to do if they say no.</p><p>Our approach to consumer negotiation combines three elements: information, preparation, and psychology. Information means knowing exactly what you are being charged and what a fair price should be. HiddenFeeAI provides this by analyzing your documents and identifying errors and overcharges. Preparation means having a clear strategy, specific talking points, and defined goals before you start negotiating. Psychology means understanding how billing departments operate and what motivates them to offer better terms.</p>';

pages['hidden-fee-database'] = '<h2>Hidden Fee Database: Searchable Directory of Charges Across Industries</h2><p>Our hidden fee database catalogs hundreds of fees charged by companies across every major industry. Each entry explains what the fee is, why it exists, whether it is legitimate or questionable, and how to challenge it. Use this database to identify unfamiliar charges on your bills and contracts, understand what they mean, and decide whether to fight them.</p><p>The database is organized by industry and fee type. Browse the categories below or use the navigation to find the specific fee you are dealing with. Each entry includes a description of the fee, typical dollar amounts, industry benchmarks, and a recommended negotiation approach.</p><p>This database is continuously updated as we identify new fees and pricing practices. If you encounter a fee that is not listed here, please let us know so we can investigate and add it.</p>';

pages['ai-invoice-analyzer'] = '<h2>AI Invoice Analyzer: Catch Hidden Charges Before You Pay</h2><p>Invoices are one of the most common sources of hidden fees and overcharges. Unlike contracts that you might review carefully before signing, invoices often get paid without a second look. This is exactly what companies count on. HiddenFeeAI\'s invoice analyzer reads every line item on your invoice and flags anything that looks incorrect, inflated, or unnecessary.</p><p>Common invoice errors include duplicate line items, charges for services not rendered, inflated material costs, unexplained administrative fees, and pricing that does not match the agreed-upon quote. The AI scans for all of these patterns and more, comparing each charge against industry benchmarks and typical pricing structures.</p><p>The process is simple. Upload your invoice in any common format, and the AI returns a detailed report within minutes. Each finding includes the specific line item, the dollar amount, an explanation of why it may be questionable, and a suggested action step. You can use this report to dispute charges with the vendor before making payment.</p>';

pages['ai-bill-analyzer'] = '<h2>AI Bill Analyzer: Find Hidden Overcharges in Every Bill You Receive</h2><p>Bills arrive every month, and most of them contain errors. Studies have shown that up to 80% of medical bills contain mistakes, and similar error rates exist across other industries. The problem is that manually reviewing every line item on every bill is time-consuming and requires expertise most people do not have. HiddenFeeAI\'s bill analyzer solves this problem by automating the review process.</p><p>The AI analyzes bills from any industry: medical, utility, phone, internet, subscription, insurance, and more. It scans for duplicate charges, rate discrepancies, unauthorized add-ons, fee increases, and billing errors. Each charge is compared against typical rates and industry standards to identify anomalies.</p>';

pages['ai-estimate-review'] = '<h2>AI Estimate Review: Verify Quotes Before You Commit</h2><p>Getting an estimate is the first step in most home improvement projects, but estimates are not always reliable. Contractors sometimes inflate prices, add unnecessary line items, or use vague language that allows them to charge more later. HiddenFeeAI\'s estimate review analyzes quotes from contractors and service providers to identify inflated pricing, hidden markups, and scope gaps that could cost you later.</p><p>The AI examines each line item in your estimate and compares it against regional averages for similar work. It flags labor rates that exceed local norms, material markups above standard industry percentages, and vague line items that lack sufficient detail. The report also identifies missing elements that should be included but are not, which can lead to change orders and cost overruns down the road.</p>';

pages['ai-quote-review'] = '<h2>AI Quote Review: Find the Best Value Across Multiple Quotes</h2><p>Getting multiple quotes is smart, but comparing them properly is hard. Contractors structure their quotes differently, include different line items, and use different pricing methodologies. HiddenFeeAI\'s quote review simplifies this by analyzing each quote against a standardized framework and highlighting the differences that matter.</p><p>When you upload multiple quotes for the same project, the AI identifies discrepancies in scope, pricing, materials, and terms. It shows you exactly where one contractor is charging more than another for the same work, and it flags hidden costs that may not be apparent from a surface-level comparison.</p>';

pages['ai-receipt-analyzer'] = '<h2>AI Receipt Analyzer: Spot Receipt Errors Instantly</h2><p>Receipts contain errors more often than most people realize. A scanner misreads a price, a cashier enters the wrong quantity, or a system adds a charge that should not be there. These errors are usually small individually, but they add up over time. HiddenFeeAI\'s receipt analyzer catches these mistakes so you can get your money back.</p><p>The AI scans every item on your receipt and checks for pricing errors, duplicate charges, incorrect tax calculations, and unauthorized fees. It compares prices against typical ranges and flags any that seem unusual.</p>';

pages['ai-contract-risk-score'] = '<h2>AI Contract Risk Score: Rate Any Agreement Before You Sign</h2><p>Every contract carries some level of risk. The question is how much. HiddenFeeAI\'s contract risk score evaluates your agreement across multiple dimensions and assigns a numerical score that tells you at a glance how risky the contract is. The score is based on the number and severity of hidden fees, one-sided clauses, pricing risks, and negotiation opportunities identified in the document.</p><p>Contracts with high risk scores typically contain multiple red flags that could cost you significantly if left unchallenged. Medium-risk contracts have some issues worth addressing. Low-risk contracts are generally fair but may still have areas worth clarifying.</p>';

for (const [name, body] of Object.entries(pages)) {
  const fp = path.join(dir, name + '.html');
  let c = fs.readFileSync(fp, 'utf8');
  const match = c.match(/<div class="long-content">([\s\S]*?)<\/div>/);
  if (match) {
    c = c.replace(match[1], '\n' + body + '\n');
    fs.writeFileSync(fp, c, 'utf8');
    console.log('Fixed: ' + name);
  } else {
    console.log('NO MATCH: ' + name);
  }
}
console.log('Group 1 done');
