name = "detecthiddenfees-business-reply"
main = "src/index.js"
compatibility_date = "2026-08-08"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "REPLY_EVENT_QUEUE"
id = "REPLACE_WITH_CLOUDFLARE_KV_NAMESPACE_ID"
